#ifndef SH_META_TYPES_H
#define SH_META_TYPES_H
enum member_type {
	type_mat4,
	type_vec4,
	type_GLuint,
	type_game_state,
	type_input_state,
	type_FILE,
	type_sh_fnt,
	type_draw_stack,
	type_sh_debug_ui_state,
	type_sh_ui_state,
	type_game_debug_func,
	type_game_init_func,
	type_game_render_func,
	type_game_update_func,
	type_GLFWwindow,
	type_objects,
	type_game_object,
	type_game_grid,
	type_uint32,
	type_FILETIME,
	type_HMODULE,
	type_sh_circle,
	type_vec2,
	type_float,
	type_int,
};
#endif SH_META_TYPES_H
